### ISSUE TITLE
生成新存档时 崩溃

### ISSUE THREAD

**Issue by OcrSu** [RoShioLeo/Contact#1]
https://pastebin.com/0KfHJU3m

**Comment by RoShioLeo** [comment]
这个主要是 vtweaks 没有按正常操作来注册导致的，以至于传入的 Capbility 是 null。
按照 Forge 的注释，这东西应该不可能为 null。
我已经从我这边的层面修复了，请更新 0.2.4 版本。
我也给对方作者发了 Issue。
