### ISSUE TITLE
with "carry on" bug to set personal mailbox

### ISSUE THREAD

**Issue by mortifia** [RoShioLeo/Contact#10]
add possibility to set command

**Comment by mortifia** [comment]
alternative to avoid to add this config
(add this mod to blacklist in carry-on
https://github.com/Tschipp/CarryOn/issues/441

**Comment by RoShioLeo** [comment]
CarryOn provides a config file to blacklist specific blocks or entire mods. Wiki [here](https://github.com/Tschipp/CarryOn/wiki/Model-Override-Config).
