### ISSUE TITLE
Server Crash When Placing Mailbox [Fabric 1.19.3, 1.0.1 Beta]

### ISSUE THREAD

**Issue by PastellePixie** [RoShioLeo/Contact#12]
[crash-2023-01-09_07.02.09-server.txt](https://github.com/lemon-slice-studio/Contact/files/10372999/crash-2023-01-09_07.02.09-server.txt)
 
Crafted a pink mailbox, went to place outside my home and it crashes the server everytime.

**Comment by RoShioLeo** [comment]
Fixed in 1.0.2
