### ISSUE TITLE
Cross Server/SinglePlayer/MP Mailing

### ISSUE THREAD

**Issue by noxnoire** [RoShioLeo/Contact#4]
loving this mod but kinda needing a feature where you:
1: can send a mail to a server from outside the server
2: optionally id also love to be able to send parcels from singleplayer to the server
been a whole day looking for a way to be able to transfer items from sp to mp seamlelly without any luck , i am aware there are flaws on doing this , but still need a way to do it

**Comment by RoShioLeo** [comment]
these features need another independent server to exchange info, like how e-mails work, which I cannot support.
network security or spam is also a problem.
