### ISSUE TITLE
Problem after breaking the mailbox

### ISSUE THREAD

**Issue by rakostep** [RoShioLeo/Contact#5]
Hi there I'd like to report an issue when a player breaks their own mailbox.  You see I was doing some renovation and stuff in my server and  tried to move my mailbox somewhere else but after placing the mailbox again, I can't claim it. Nothing happens if I sneak+click on it. However if I send stuff(to myself) it somehow locates it to another location(I can't track it, can't find a way to know the coordinates).

Not sure if I missed some instructions and stuff but if I do, please let me know.

Thanks for reading through this small issue.

**Comment by RoShioLeo** [comment]
It seemed that you clicked on it with something in your hands.
If so, try it again with nothing held. Please do not hold anything in your hands.
Default location is (0,0).
And Center Mailbox is designed for those who don't have their own mailboxes. It can be only placed by op.

Thank you for enjoying my mod.

**Comment by rakostep** [comment]
Hi again, sorry for the late reply. I did try it with nothing on my hand, unless that includes nothing on the offhand also?

**Comment by RoShioLeo** [comment]
Yes.
It's Minecraft's feature.
