### ISSUE TITLE
More items to send through mail without Parcel

### ISSUE THREAD

**Issue by VanderCat** [RoShioLeo/Contact#6]
Hello, i'm really like the idea of the mod, but i think it lacks a way to add more items to send through mail. So there's mod called Supplementaries which adds a present box, like a parcel but placeable and only for one stack of items. It would be cool if i could send this like a parcel through Mailbox. You can see the description [here](https://github.com/MehVahdJukaar/Supplementaries/wiki/Decorative-Blocks#present).

I checked the code and found out i can only send items through mail if they're implementing `IMailItem`, so i would suggest also allow sending items if they have an NBT tag or whitelisted in config.

Thank you for such an amazing mod.

**Comment by RoShioLeo** [comment]
Thank you! I know Supplementaries, a very elegant mod.
But I think parcel is enough. There is no need to add more complex methods.
For personal reasons, I can't put more effort into development.
I'm sorry.
