### ISSUE TITLE
Lose item in Wrapping Paper UI

### ISSUE THREAD

**Issue by UDTakerBean** [RoShioLeo/Contact#8]
Clicking the Pack button while Cursor is holding an item causes the item to be lost

For example, Apple just disappears and is not in the Parcel or Player Inventory after wrapping.

![issue](https://user-images.githubusercontent.com/31041335/197375092-e832d4fe-4cde-4ee3-8c13-bdf5ea83c1ae.png)

Version: 1.18.2-1.1.3
Forge 40.1.79

**Comment by RoShioLeo** [comment]
Fixed in 1.19.3-2.0.1
