### ISSUE TITLE
Fabric 1.18.2

### ISSUE THREAD

**Issue by 5ur3z** [RoShioLeo/Contact#9]
Is there any plan porting to Fabric 1.18.2?

**Comment by RoShioLeo** [comment]
Work in process. But it's a bit complex.

**Comment by RoShioLeo** [comment]
I made it in 1.19.3. But I have no plan to port to 1.18.2.

**Comment by 5ur3z** [comment]
> I made it in 1.19.3. But I have no plan to port to 1.18.2.

any plan for porting to 1.19.2 fabric?
I've just upgrade my server to 1.19.2
